export const cars = [
  {
    id: 1001,
    name: 'TESLA Model X Dual Motor & Long Range - 2018',
    year: 2018,
    price: 0,
    originalPrice: 0,
    image: '/Tesla Model X/1.jpg',
    brand: 'Tesla',
    model: 'Model X',
    mileage: 33500,
    bodyStyle: 'Compact SUV',
    fuel: 'Electric',
    transmission: 'AWD/4WD',
    engine: 'Electric Power = 350 kW (469 hp), Torque = 600 Nm, RPM = 6100',
    location: 'Un-Registered, Import from Japan',
    badges: ['Used', '7 Seater', '4 Grade Auction Sheet', 'Fresh Import 2024'],
    features: [
      'Beautiful Pearl White Color',
      'Milky Cream White Interior',
      'Range 450 Km with A/C at Full Charged',
      'Full Charging within 40 Minutes at Commercial Charging Station',
      'Almost 6 Hours needed at House Portable Charging Adaptor',
      'Top Speed = 225 Km/Hr',
      'Acceleration from 0 to 100 km/h in 4.40 Seconds',
      'AWD Drivetrain',
      'Smart Air Suspension at Front & Back',
      'Brand New and Immaculate Condition Guaranteed (ALHAMDULILLAH)',
      'Much More Details are available upon demand'
    ],
    gallery: [
      '/Tesla Model X/1.jpg',
      '/Tesla Model X/2.jpg',
      '/Tesla Model X/3.jpg',
      '/Tesla Model X/4.jpg',
      '/Tesla Model X/5.jpg',
      '/Tesla Model X/6.jpg',
      '/Tesla Model X/7.jpg',
      '/Tesla Model X/8.jpg',
      '/Tesla Model X/9.jpg',
      '/Tesla Model X/10.jpg',
      '/Tesla Model X/11.jpg',
      '/Tesla Model X/12.jpg',
      '/Tesla Model X/13.jpg',
      '/Tesla Model X/14.jpg'
    ],
    description: `Model Year: 2018\nImport: Fresh import from Japan (2024)\nCondition: Brand new and immaculate (4 Grade Auction Sheet)\nSeating: 7 Seater\nColor: Beautiful Pearl White exterior with Milky Cream White interior\n\nPerformance & Power:\n- Electric Power: 350 kW (469 hp)\n- Torque: 600 Nm\n- Top Speed: 225 km/h\n- Acceleration: 0 to 100 km/h in 4.4 seconds\n- Drivetrain: All-Wheel Drive (AWD)\n- Suspension: Smart Air Suspension (front & rear)\n\nRange & Charging:\n- Range: 450 km with A/C on a full charge\n- Charging Time:\n  • 40 minutes at commercial fast charging stations\n  • Approximately 6 hours with home portable charging adaptor`,
    specifications: {
      'Model Year': '2018',
      'Mileage': '33,500 KM',
      'Body Style': 'Compact SUV',
      'Fuel Type': 'Electric',
      'Drive Type': 'AWD/4WD',
      'Seating Capacity': '7',
      'Auction Grade': '4',
      'Color': 'Pearl White',
      'Interior': 'Milky Cream White',
      'Range (Full Charge)': '450 Km (A/C On)',
      'Charging Time (Commercial)': '40 Minutes',
      'Charging Time (Home)': '6 Hours',
      'Electric Power': '350 kW',
      'Mechanical Power': '469 hp',
      'Torque': '600 Nm',
      'RPM': '6100',
      'Top Speed': '225 Km/Hr',
      '0-100 km/h': '4.40 Seconds',
      'Suspension': 'Smart Air Suspension (Front & Back)',
      'Condition': 'Brand New & Immaculate (ALHAMDULILLAH)'
    }
  },
  {
    id: 1002,
    name: 'TESLA Model X Dual Motor & Long Range - 2018 (Grey)',
    year: 2018,
    price: 0,
    originalPrice: 0,
    image: '/Tesla Model X Grey/1.jpg',
    brand: 'Tesla',
    model: 'Model X',
    mileage: 33500,
    bodyStyle: 'Compact SUV',
    fuel: 'Electric',
    transmission: 'AWD/4WD',
    engine: 'Electric Power = 350 kW (469 hp), Torque = 600 Nm, RPM = 6100',
    location: 'Un-Registered, Import from Japan',
    badges: ['Used', '7 Seater', '4.5 Grade Auction Sheet', 'Fresh Import 2023'],
    features: [
      'Silky Grey Exterior',
      'Milky Cream White Interior',
      '7 Seater',
      'Auction Grade 4.5 – Verified Clean Condition',
      'Smart Air Suspension (Front & Rear)',
      'All-Wheel Drive (AWD)',
      'Up to 450 km Range (A/C On)',
      'Fast Charging: 60 min (Commercial)',
      'Home Charging: 6 hours',
      'Immaculate Condition Guaranteed'
    ],
    gallery: [
      '/Tesla Model X Grey/1.jpg',
      '/Tesla Model X Grey/2.jpg',
      '/Tesla Model X Grey/3.jpg',
      '/Tesla Model X Grey/4.jpg',
      '/Tesla Model X Grey/5.jpg',
      '/Tesla Model X Grey/6.jpg',
      '/Tesla Model X Grey/7.jpg',
      '/Tesla Model X Grey/8.jpg',
      '/Tesla Model X Grey/9.jpg',
      '/Tesla Model X Grey/10.jpg',
      '/Tesla Model X Grey/11.jpg',
      '/Tesla Model X Grey/12.jpg',
      '/Tesla Model X Grey/13.jpg',
      '/Tesla Model X Grey/14.jpg'
    ],
    description: `Model Year: 2018\nImport: Imported from Japan in 2023\nAuction Grade: 4.5 Grade – Verified Clean Condition\nSeating Capacity: 7 Seater\nColor: Silky Grey Exterior with Milky Cream White Interior\n\nPerformance & Power:\n- Electric Power: 350 kW (469 hp)\n- Torque: 600 Nm\n- RPM: 6100\n- Top Speed: 225 km/h\n- Acceleration: 0 to 100 km/h in just 4.4 seconds\n- Drivetrain: All-Wheel Drive (AWD)\n- Suspension: Smart Air Suspension (Front & Rear)\n\nRange & Charging:\n- Range: Up to 450 km with A/C on full charge\n- Charging Time:\n  • About 60 minutes at commercial charging stations\n  • Around 6 hours with home portable charger\n\nGuaranteed immaculate condition.\n\nFor more details, feel free to contact us!`,
    specifications: {
      'Model Year': '2018',
      'Import': 'Japan (2023)',
      'Auction Grade': '4.5',
      'Seating Capacity': '7',
      'Color': 'Silky Grey',
      'Interior': 'Milky Cream White',
      'Electric Power': '350 kW (469 hp)',
      'Torque': '600 Nm',
      'RPM': '6100',
      'Top Speed': '225 km/h',
      '0-100 km/h': '4.4 seconds',
      'Drivetrain': 'AWD',
      'Suspension': 'Smart Air Suspension (Front & Rear)',
      'Range': 'Up to 450 km (A/C On)',
      'Charging Time (Commercial)': '60 min',
      'Charging Time (Home)': '6 hours',
      'Condition': 'Immaculate'
    }
  },
  {
    id: 1003,
    name: 'Toyota Prius HEV - 2023',
    year: 2023,
    price: 0,
    originalPrice: 0,
    image: '/Toyota Prius/1.jpg',
    brand: 'Toyota',
    model: 'Prius HEV',
    mileage: 8000,
    bodyStyle: 'Sedan',
    fuel: 'Hybrid',
    transmission: 'ECVT',
    engine: 'Hybrid System Net Power 194 hp (FWD) or 196 hp',
    location: 'Punjab',
    badges: ['Used', '4 Doors', 'Registered 2024'],
    features: [
      'ABS',
      'Air Conditioning',
      'Alloy Rims',
      'AM/FM Radio',
      'Bluetooth',
      'Cruise Control',
      'Electric Adjustable Seats',
      'Front Speakers',
      'Immobilizer Key',
      'Keyless Entry',
      'Keyless start',
      'Navigation System',
      'Power Locks',
      'Power Mirrors',
      'Power Seats',
      'Power Steering',
      'Power Windows',
      'Rear Camera',
      'Touchscreen LCD',
      'USB and Auxillary Cable'
    ],
    gallery: [
      '/Toyota Prius/1.jpg',
      '/Toyota Prius/2.jpg',
      '/Toyota Prius/3.jpg',
      '/Toyota Prius/4.jpg',
      '/Toyota Prius/5.jpg',
      '/Toyota Prius/6.jpg',
      '/Toyota Prius/7.jpg',
      '/Toyota Prius/8.jpg',
      '/Toyota Prius/9.jpg',
      '/Toyota Prius/10.jpg',
      '/Toyota Prius/11.jpg',
      '/Toyota Prius/12.jpg',
      '/Toyota Prius/13.jpg',
      
    ],
    description: `Toyota Prius Top Of the Line U Package\nModel – 2023\nRegistered – 2024\nHorsepower 150 hp @ 6000 rpm, 139 lb. -ft. @ 4400-5200 rpm.\nHybrid System Net Power 194 hp (FWD) or 196 hp.\nTransmission: Electronically controlled Continuously Variable Transmission (ECVT)\nDrive Type Front-Wheel Drive (FWD) or All-Wheel Drive (AWD).\n0-60 mph: 7.2 seconds.\nBrakes: 11.1-in vented disc/11.0-in disc.\nEntertainment Standard Bluetooth\n\nTons of much more features………………\nBrand New and Immaculate Condition Guaranteed (ALHAMDULILLAH)`,
    specifications: {
      'Model Year': '2023',
      'Registration': '2024',
      'Mileage': '8,000 KM',
      'Body Style': 'Sedan',
      'Fuel Type': 'Hybrid',
      'Doors': '4',
      'Horsepower': '150 hp @ 6000 rpm',
      'Torque': '139 lb.-ft. @ 4400-5200 rpm',
      'Hybrid System Net Power': '194 hp (FWD) / 196 hp',
      'Transmission': 'ECVT',
      'Drive Type': 'FWD / AWD',
      '0-60 mph': '7.2 seconds',
      'Brakes': '11.1-in vented disc/11.0-in disc',
      'Entertainment': 'Bluetooth',
      'Condition': 'Brand New & Immaculate (ALHAMDULILLAH)'
    }
  },
  {
    id: 1004,
    name: 'Toyota Raize Z - 2020',
    year: 2020,
    price: 0,
    originalPrice: 0,
    image: '/Toyota Raize XS - 2020/1.jpg',
    brand: 'Toyota',
    model: 'Raize Z',
    mileage: 56610,
    bodyStyle: 'SUV',
    fuel: 'Petrol',
    transmission: 'Automatic',
    engine: '—',
    location: 'Un-Registered, Import from Japan',
    badges: ['Used', '4 Doors', 'Top of the Line Z Package', '4.5 Grade Auction Sheet', 'Fresh Import 2025'],
    features: [
      'ABS',
      'Air Bags',
      'Air Conditioning',
      'Alloy Rims',
      'AM/FM Radio',
      'Climate Control',
      'Cruise Control',
      'DVD Player',
      'Front Speakers',
      'Immobilizer Key',
      'Keyless Entry',
      'Navigation System',
      'Power Locks',
      'Power Mirrors',
      'Power Steering',
      'Power Windows',
      'Rear Camera',
      'Rear Speakers',
      'Steering Switches',
      'USB and Auxillary Cable',
      'TOYOTA Safety Sense with Anti Collision System',
      'Adaptive Cruise Control With Radar',
      '360 Cameras',
      'Push Start, Key-Less Entry',
      'Latest Dual Eco Idling Technology for Maximum Fuel Efficiency with 18-20 Km/L',
      'Full Multimedia Steering',
      'TOYOTA Original LCD, Navigation, Bluetooth, Back Camera',
      'Retractable Side Mirrors',
      'Ultraviolet Glass Protection',
      'ABS Brakes with EBD Break Assist',
      'Active Headrest',
      'Climate Control Full Auto AC',
      'Genuine 17″ Alloy Rims',
      'LED Projector Head Beams',
      'Brand New & Immaculate Condition Guaranteed (In Sha Allah)'
    ],
    gallery: [
      '/Toyota Raize XS - 2020/1.jpg',
      '/Toyota Raize XS - 2020/2.jpg',
      '/Toyota Raize XS - 2020/3.jpg',
      '/Toyota Raize XS - 2020/4.jpg',
      '/Toyota Raize XS - 2020/5.jpg',
      '/Toyota Raize XS - 2020/6.jpg',
      '/Toyota Raize XS - 2020/7.jpg',
      '/Toyota Raize XS - 2020/8.jpg',
      '/Toyota Raize XS - 2020/9.jpg',
      '/Toyota Raize XS - 2020/10.jpg',
      '/Toyota Raize XS - 2020/11.jpg'
    ],
    description: `TOYOTA RAIZE\nModel Year 2020\nImport Year 2025\nTop of the Line Z Package\n4.5 Grade Verifiable Auction Sheet\nNew Elegant Muscular Shape\nBeautiful Aggressive Black Color\nBeautiful New Interior\nTOYOTA Safety Sense with Anti Collision System\nAdaptive Cruise Control With Radar\n360 Cameras\nPush Start, Key-Less Entry\nLatest Dual Eco Idling Technology for Maximum Fuel Efficiency with 18-20 Km/L\nFull Multimedia Steering\nTOYOTA Original LCD, Navigation, Bluetooth, Back Camera\nRetractable Side Mirrors\nUltraviolet Glass Protection\nABS Brakes with EBD Break Assist\nActive Headrest\nClimate Control Full Auto AC\nGenuine 17″ Alloy Rims\nLED Projector Head Beams\n\nBrand New & Immaculate Condition Guaranteed (In Sha Allah)`,
    specifications: {
      'Model Year': '2020',
      'Import Year': '2025',
      'Mileage': '56,610 KM',
      'Body Style': 'SUV',
      'Fuel Type': 'Petrol',
      'Doors': '4',
      'Condition': 'Used',
      'Auction Grade': '4.5',
      'Package': 'Top of the Line Z',
      'Color': 'Aggressive Black',
      'Interior': 'New Interior',
      'Safety': 'TOYOTA Safety Sense, Anti Collision System',
      'Cruise Control': 'Adaptive with Radar',
      'Cameras': '360 Cameras',
      'Entry': 'Push Start, Key-Less',
      'Eco Technology': 'Dual Eco Idling, 18-20 Km/L',
      'Steering': 'Full Multimedia',
      'Infotainment': 'TOYOTA LCD, Navigation, Bluetooth, Back Camera',
      'Mirrors': 'Retractable Side',
      'Glass': 'Ultraviolet Protection',
      'Brakes': 'ABS, EBD Break Assist',
      'Headrest': 'Active',
      'AC': 'Climate Control Full Auto',
      'Rims': 'Genuine 17″ Alloy',
      'Head Beams': 'LED Projector',
      'Guarantee': 'Brand New & Immaculate (In Sha Allah)'
    }
  },
  {
    id: 1005,
    name: 'Honda Civic Oriel 1.8 i-VTEC - 2018',
    year: 2018,
    price: 0,
    originalPrice: 0,
    image: '/Civic/1.jpg',
    brand: 'Honda',
    model: 'Civic Oriel 1.8 i-VTEC',
    mileage: 31000,
    bodyStyle: 'Sedan',
    fuel: 'Petrol',
    transmission: 'Automatic',
    engine: '1.8L - X UG Leather Package',
    location: 'Registered: Punjab',
    badges: ['Used', '4-door', 'Sunroof', 'Push Start', 'Smart Entry',],
    features: [
      'Beautiful Silver Color, High Re-Sale Value',
      '100% Genuine Mileage',
      '100% B2B Genuine',
      'Good Fuel Average Due to Auto Eco Idle Mode',
      'Genuine DVD, FM, Navigation, Back View CAM, Bluetooth',
      '2 Tone beautiful Beige Grey Interior',
      'Winker Type Retractable Indicators',
      'ABS Brakes with EBD Break Assist',
      'Active Headrest',
      'Climate Control Full Auto A/C',
      'Auto Dusk Sensor HID Projector Head Lights',
      'Genuine FOG Lights',
      'Brand New & Immaculate Condition Guaranteed (In Sha Allah)'
    ],
    gallery: [
      '/Civic/1.jpg',
      '/Civic/2.jpg',
      '/Civic/3.jpg',
      '/Civic/4.jpg',
      '/Civic/5.jpg',
      '/Civic/6.jpg',
      '/Civic/7.jpg',
      '/Civic/8.jpg',
      '/Civic/9.jpg',
      '/Civic/10.jpg',
      '/Civic/11.jpg',
      '/Civic/12.jpg',
      '/Civic/13.jpg'
    ],
    description: `Honda Civic Oriel 1.8 i-VTEC - 2018\n2018\n31,000 KM\nSedan\nPetrol\nCall for Price\nFuel Type: Petrol\nDoors: 4-door\nRegistered: Punjab\nHONDA CIVIC 1.8L - X UG Leather Package\nSunroof\nPush Start / Smart Entry\nBeautiful Silver Color, High Re-Sale Value\n100% Genuine Mileage\n100% B2B Genuine\nGood Fuel Average Due to Auto Eco Idle Mode\nGenuine DVD, FM, Navigation, Back View CAM, Bluetooth\n2 Tone beautiful Beige Grey Interior\nWinker Type Retractable Indicators\nABS Brakes with EBD Break Assist\nActive Headrest\nClimate Control Full Auto A/C\nAuto Dusk Sensor HID Projector Head Lights\nGenuine FOG Lights\n\nBrand New & Immaculate Condition Guaranteed (In Sha Allah)`,
    specifications: {
      'Model Year': '2018',
      'Mileage': '31,000 KM',
      'Body Style': 'Sedan',
      'Fuel Type': 'Petrol',
      'Doors': '4',
      'Registration': 'Punjab',
      'Package': '1.8L - X UG Leather',
      'Sunroof': 'Yes',
      'Push Start': 'Yes',
      'Smart Entry': 'Yes',
      'Color': 'Silver',
      'Interior': '2 Tone Beige Grey',
      'Indicators': 'Winker Type Retractable',
      'Brakes': 'ABS with EBD Break Assist',
      'Headrest': 'Active',
      'A/C': 'Climate Control Full Auto',
      'Head Lights': 'Auto Dusk Sensor HID Projector',
      'Fog Lights': 'Genuine',
      'Condition': 'Brand New & Immaculate (In Sha Allah)'
    }
  },
  {
    id: 1006,
    name: 'Nissan Kicks - 2021',
    year: 2021,
    price: 0,
    originalPrice: 0,
    image: '/Nissan kicks/10.jpg',
    brand: 'Nissan',
    model: 'Kicks',
    mileage: 42000,
    bodyStyle: 'Crossover',
    fuel: 'Petrol',
    transmission: 'Automatic',
    engine: '1300 cc',
    location: 'Registered In Punjab',
    badges: ['Used', '4 Doors', 'Imported', 'White Color'],
    features: [
      'Beautiful White Color',
      'Imported Assembly',
      '1300 cc Engine Capacity',
      'Crossover Body Type',
      'ABS Brakes',
      'AM/FM Radio',
      'Air Bags',
      'Air Conditioning',
      'Alloy Rims',
      'CoolBox',
      'Cruise Control',
      'Immobilizer Key',
      'Keyless Entry',
      'Navigation System',
      'Power Locks',
      'Power Mirrors',
      'Power Steering',
      'Power Windows',
      'Brand New & Immaculate Condition Guaranteed (In Sha Allah)'
    ],
    gallery: [
      '/Nissan kicks/1.jpg',
      '/Nissan kicks/2.jpg',
      '/Nissan kicks/3.jpg',
      '/Nissan kicks/4.jpg',
      '/Nissan kicks/5.jpg',
      '/Nissan kicks/6.jpg',
      '/Nissan kicks/7.jpg',
      '/Nissan kicks/8.jpg',
      '/Nissan kicks/9.jpg',
      '/Nissan kicks/10.jpg',
      '/Nissan kicks/11.jpg',
      '/Nissan kicks/12.jpg'
    ],
    description: `NISSAN KICKS - 2021\nModel Year: 2021\nMileage: 42,000 km\nFuel Type: Petrol\nTransmission: Automatic\nRegistered In: Punjab\nColor: White\nAssembly: Imported\nEngine Capacity: 1300 cc\nBody Type: Crossover\nLast Updated: Aug 02, 2025\nAd Ref #: 10320403\n\nFeatures:\nABS Brakes\nAM/FM Radio\nAir Bags\nAir Conditioning\nAlloy Rims\nCoolBox\nCruise Control\nImmobilizer Key\nKeyless Entry\nNavigation System\nPower Locks\nPower Mirrors\nPower Steering\nPower Windows\n\nBrand New & Immaculate Condition Guaranteed (In Sha Allah)`,
    specifications: {
      'Model Year': '2021',
      'Mileage': '42,000 KM',
      'Body Style': 'Crossover',
      'Fuel Type': 'Petrol',
      'Transmission': 'Automatic',
      'Registration': 'Punjab',
      'Color': 'White',
      'Assembly': 'Imported',
      'Engine Capacity': '1300 cc',
      'Body Type': 'Crossover',
      'Last Updated': 'Aug 02, 2025',
      'Ad Ref #': '10320403',
      'ABS': 'Yes',
      'AM/FM Radio': 'Yes',
      'Air Bags': 'Yes',
      'Air Conditioning': 'Yes',
      'Alloy Rims': 'Yes',
      'CoolBox': 'Yes',
      'Cruise Control': 'Yes',
      'Immobilizer Key': 'Yes',
      'Keyless Entry': 'Yes',
      'Navigation System': 'Yes',
      'Power Locks': 'Yes',
      'Power Mirrors': 'Yes',
      'Power Steering': 'Yes',
      'Power Windows': 'Yes',
      'Condition': 'Brand New & Immaculate (In Sha Allah)'
    }
  },
  {
    id: 1007,
    name: 'Toyota Aqua S - 2020',
    year: 2020,
    price: 0,
    originalPrice: 0,
    image: '/toyota aqua prius/7.jpg',
    brand: 'Toyota',
    model: 'Aqua S',
    mileage: 108500,
    bodyStyle: 'Hatchback',
    fuel: 'Hybrid',
    transmission: 'Automatic',
    engine: '1500 cc',
    location: 'Un-Registered, Import from Japan',
    badges: ['Used', '4 Doors', 'Hybrid', 'Imported', 'Silver Color'],
    features: [
      'ABS',
      'AM/FM Radio',
      'Air Bags',
      'Air Conditioning',
      'Immobilizer Key',
      'Keyless Entry',
      'Power Locks',
      'Power Mirrors',
      'Power Steering',
      'Power Windows',
      'TOYOTA AQUA MODEL 2020',
      'IMPORT 2024',
      '4 GRADE VERIFIED AUCTION SHEET',
      '30 KM/L MILAGE',
      'JUST BUY AND DRIVE'
    ],
    gallery: [
      '/toyota aqua prius/1.jpg',
      '/toyota aqua prius/2.jpg',
      '/toyota aqua prius/3.jpg',
      '/toyota aqua prius/4.jpg',
      '/toyota aqua prius/5.jpg',
      '/toyota aqua prius/6.jpg',
      '/toyota aqua prius/7.jpg',
      '/toyota aqua prius/8.jpg',
      '/toyota aqua prius/9.jpg',
      '/toyota aqua prius/10.jpg',
      '/toyota aqua prius/11.jpg',
      '/toyota aqua prius/12.jpg',
      '/toyota aqua prius/13.jpg',
      '/toyota aqua prius/14.jpg'
    ],
    description: `Toyota Aqua S - 2020\nModel Year: 2020\nMileage: 108,500 km\nFuel Type: Hybrid\nTransmission: Automatic\nRegistration: Un-Registered\nColor: Silver\nAssembly: Imported\nEngine Capacity: 1500 cc\nBody Type: Hatchback\nLast Updated: Aug 02, 2025\nAd Ref #: 10155801\n\nFeatures:\nABS\nAM/FM Radio\nAir Bags\nAir Conditioning\nImmobilizer Key\nKeyless Entry\nPower Locks\nPower Mirrors\nPower Steering\nPower Windows\nTOYOTA AQUA MODEL 2020\nIMPORT 2024\n4 GRADE VERIFIED AUCTION SHEET\n30 KM/L MILAGE\nJUST BUY AND DRIVE\n\nBrand New & Immaculate Condition Guaranteed (ALHAMDULILLAH)`,
    specifications: {
      'Model Year': '2020',
      'Mileage': '108,500 KM',
      'Body Style': 'Hatchback',
      'Fuel Type': 'Hybrid',
      'Transmission': 'Automatic',
      'Registration': 'Un-Registered',
      'Color': 'Silver',
      'Assembly': 'Imported',
      'Engine Capacity': '1500 cc',
      'Body Type': 'Hatchback',
      'Last Updated': 'Aug 02, 2025',
      'Ad Ref #': '10155801',
      'ABS': 'Yes',
      'AM/FM Radio': 'Yes',
      'Air Bags': 'Yes',
      'Air Conditioning': 'Yes',
      'Immobilizer Key': 'Yes',
      'Keyless Entry': 'Yes',
      'Power Locks': 'Yes',
      'Power Mirrors': 'Yes',
      'Power Steering': 'Yes',
      'Power Windows': 'Yes',
      'Auction Grade': '4',
      'Import Year': '2024',
      'Fuel Efficiency': '30 KM/L',
      'Condition': 'Brand New & Immaculate (ALHAMDULILLAH)'
    }
  },
  {
    id: 1008,
    name: 'Toyota Corolla Altis Grande X CVT-i 1.8 - 2021',
    year: 2021,
    price: 0,
    originalPrice: 0,
    image: '/Toyota Corolla grande/6.jpg',
    brand: 'Toyota',
    model: 'Corolla Altis Grande X CVT-i 1.8',
    mileage: 45000,
    bodyStyle: 'Sedan',
    fuel: 'Petrol',
    transmission: 'CVT',
    engine: '1800 cc',
    location: 'Registered In Punjab',
    badges: ['Used', '4 Doors', 'Local Assembly', 'White Color', 'Sunroof'],
    features: [
      'Beautiful White Color with Beige Interior',
      'Local Assembly',
      '1800 cc Engine Capacity',
      'CVT-i Transmission',
      'Sunroof',
      'ABS Brakes',
      'AM/FM Radio',
      'Air Bags',
      'Air Conditioning',
      'Alloy Rims',
      'Cruise Control',
      'Immobilizer Key',
      'Keyless Entry',
      'Navigation System',
      'Power Locks',
      'Power Mirrors',
      'Power Steering',
      'Power Windows',
      'Touchscreen Display',
      'Bluetooth Connectivity',
      'Rear Camera',
      'Climate Control',
      'Brand New & Immaculate Condition Guaranteed (In Sha Allah)'
    ],
    gallery: [
      '/Toyota Corolla grande/1.jpg',
      '/Toyota Corolla grande/2.jpg',
      '/Toyota Corolla grande/3.jpg',
      '/Toyota Corolla grande/4.jpg',
      '/Toyota Corolla grande/5.jpg',
      '/Toyota Corolla grande/6.jpg',
      '/Toyota Corolla grande/7.jpg',
      '/Toyota Corolla grande/8.jpg',
      '/Toyota Corolla grande/9.jpg',
      '/Toyota Corolla grande/10.jpg',
      '/Toyota Corolla grande/11.jpg',
      '/Toyota Corolla grande/12.jpg',
      '/Toyota Corolla grande/13.jpg',
      '/Toyota Corolla grande/14.jpg',
      '/Toyota Corolla grande/15.jpg'
    ],
    description: `Toyota Corolla Altis Grande X CVT-i 1.8 - 2021\nModel Year: 2021\nMileage: 45,000 km\nFuel Type: Petrol\nTransmission: CVT-i\nRegistration: Punjab\nColor: White with Beige Interior\nAssembly: Local\nEngine Capacity: 1800 cc\nBody Type: Sedan\nLast Updated: Aug 02, 2025\nAd Ref #: 10395995\n\nFeatures:\nABS Brakes\nAM/FM Radio\nAir Bags\nAir Conditioning\nAlloy Rims\nCruise Control\nImmobilizer Key\nKeyless Entry\nNavigation System\nPower Locks\nPower Mirrors\nPower Steering\nPower Windows\nSunroof\nTouchscreen Display\nBluetooth Connectivity\nRear Camera\nClimate Control\n\nBrand New & Immaculate Condition Guaranteed (In Sha Allah)`,
    specifications: {
      'Model Year': '2021',
      'Mileage': '45,000 KM',
      'Body Style': 'Sedan',
      'Fuel Type': 'Petrol',
      'Transmission': 'CVT-i',
      'Registration': 'Punjab',
      'Color': 'White',
      'Interior': 'Beige',
      'Assembly': 'Local',
      'Engine Capacity': '1800 cc',
      'Body Type': 'Sedan',
      'Last Updated': 'Aug 02, 2025',
      'Ad Ref #': '10395995',
      'ABS': 'Yes',
      'AM/FM Radio': 'Yes',
      'Air Bags': 'Yes',
      'Air Conditioning': 'Yes',
      'Alloy Rims': 'Yes',
      'Cruise Control': 'Yes',
      'Immobilizer Key': 'Yes',
      'Keyless Entry': 'Yes',
      'Navigation System': 'Yes',
      'Power Locks': 'Yes',
      'Power Mirrors': 'Yes',
      'Power Steering': 'Yes',
      'Power Windows': 'Yes',
      'Sunroof': 'Yes',
      'Touchscreen Display': 'Yes',
      'Bluetooth Connectivity': 'Yes',
      'Rear Camera': 'Yes',
      'Climate Control': 'Yes',
      'Condition': 'Brand New & Immaculate (In Sha Allah)'
    }
  },
  {
    id: 1009,
    name: 'Toyota Prado TX L Package 2.7 - 2010',
    year: 2010,
    price: 0,
    originalPrice: 0,
    image: '/Toyota Land Cruser/2.jpg',
    brand: 'Toyota',
    model: 'Prado TX L Package 2.7',
    mileage: 89000,
    bodyStyle: 'SUV',
    fuel: 'Petrol',
    transmission: 'Automatic',
    engine: '2700 cc',
    location: 'Registered In Punjab',
    badges: ['Used', '5 Doors', 'Imported Assembly', 'White Color', 'L Package'],
    features: [
      'Beautiful White Color',
      'Imported Assembly',
      '2700 cc Engine Capacity',
      'SUV Body Type',
      'TX L Package',
      'Uplifted to 2018 Model',
      'Total Genuine - Still Like Zero Meter Car',
      'Verified Auction Sheet Available',
      'All Old Parts Available',
      'ABS Brakes',
      'AM/FM Radio',
      'Air Bags',
      'Air Conditioning',
      'Alloy Rims',
      'CD Player',
      'CoolBox',
      'Cruise Control',
      'DVD Player',
      'Immobilizer Key',
      'Keyless Entry',
      'Power Locks',
      'Power Mirrors',
      'Power Steering',
      'Power Windows',
      'Brand New & Immaculate Condition Guaranteed (In Sha Allah)'
    ],
    gallery: [
      '/Toyota Land Cruser/1.jpg',
      '/Toyota Land Cruser/2.jpg',
      '/Toyota Land Cruser/3.jpg',
      '/Toyota Land Cruser/4.jpg',
      '/Toyota Land Cruser/5.jpg',
      '/Toyota Land Cruser/6.jpg',
      '/Toyota Land Cruser/7.jpg',
      '/Toyota Land Cruser/8.jpg',
      '/Toyota Land Cruser/9.jpg',
      '/Toyota Land Cruser/10.jpg',
      '/Toyota Land Cruser/11.jpg',
      '/Toyota Land Cruser/12.jpg',
      '/Toyota Land Cruser/13.jpg',
      '/Toyota Land Cruser/14.jpg',
      '/Toyota Land Cruser/15.jpg'
    ],
    description: `Toyota Prado TX L Package 2.7 - 2010\nModel Year: 2010\nMileage: 89,000 km\nFuel Type: Petrol\nTransmission: Automatic\nRegistration: Punjab\nColor: White\nAssembly: Imported\nEngine Capacity: 2700 cc\nBody Type: SUV\nLast Updated: Aug 02, 2025\nAd Ref #: 10153941\n\nPackage: TX L Package\nImport Year: 2015\nUplifted to 2018 Model\nTotal Genuine - Still Like Zero Meter Car\nVerified Auction Sheet Available\nAll Old Parts Available\n\nFeatures:\nABS Brakes\nAM/FM Radio\nAir Bags\nAir Conditioning\nAlloy Rims\nCD Player\nCoolBox\nCruise Control\nDVD Player\nImmobilizer Key\nKeyless Entry\nPower Locks\nPower Mirrors\nPower Steering\nPower Windows\n\nBrand New & Immaculate Condition Guaranteed (In Sha Allah)`,
    specifications: {
      'Model Year': '2010',
      'Mileage': '89,000 KM',
      'Body Style': 'SUV',
      'Fuel Type': 'Petrol',
      'Transmission': 'Automatic',
      'Registration': 'Punjab',
      'Color': 'White',
      'Assembly': 'Imported',
      'Engine Capacity': '2700 cc',
      'Body Type': 'SUV',
      'Package': 'TX L Package',
      'Import Year': '2015',
      'Uplifted Model': '2018',
      'Last Updated': 'Aug 02, 2025',
      'Ad Ref #': '10153941',
      'ABS': 'Yes',
      'AM/FM Radio': 'Yes',
      'Air Bags': 'Yes',
      'Air Conditioning': 'Yes',
      'Alloy Rims': 'Yes',
      'CD Player': 'Yes',
      'CoolBox': 'Yes',
      'Cruise Control': 'Yes',
      'DVD Player': 'Yes',
      'Immobilizer Key': 'Yes',
      'Keyless Entry': 'Yes',
      'Power Locks': 'Yes',
      'Power Mirrors': 'Yes',
      'Power Steering': 'Yes',
      'Power Windows': 'Yes',
      'Condition': 'Brand New & Immaculate (In Sha Allah)'
    }
  },
  {
    id: 1014,
    name: 'NISSAN Note e-Power Hybrid - 2021',
    year: 2021,
    price: 0,
    originalPrice: 0,
    image: '/Nissasn Note E/1.jpg',
    brand: 'Nissan',
    model: 'NOTE ePOWER',
    mileage: 30000,
    bodyStyle: 'Hatchback',
    fuel: 'Hybrid',
    transmission: 'Automatic',
    engine: '1.2L e-Power Full Hybrid',
    location: 'Un-Registered, Fresh Import July 2024',
    badges: ['Used', '4 Doors', 'Fresh Import 2024', 'Pearl Silver'],
    features: [
      'Full Hybrid e-Power System (1.2L)',
      'Fresh Import July 2024',
      'Medalist Package',
      'Verifiable Auction Sheet',
      'Beautiful Pearl Silver Color',
      'Genuine 28,000 KM Driven in Japan',
      'Like a Zero Meter Car',
      'Anti Lane Assist',
      'NISSAN Safety Sense with Anti Collision System',
      'NISSAN Original DVD Player, FM, Navigation with 5 View Cameras',
      'Full Multimedia Steering',
      'Cruise Control, ACCA RADAR, Pro Pilot',
      'Push Start & Key-Less Entry',
      'Japanese Original Security Alarm System',
      'LED Projector Head Beams with Genuine FOG Lamps',
      '3 Driving Modes (Normal, Power, Eco)',
      'Standard 6 Air Bags',
      'Winker Type Side Mirrors',
      'Fuel Average 25+ KM/L (Verifiable on Nissan Official Website)',
      'Ultraviolet Glass Protection',
      'ABS Brakes',
      'Driver Arm Rest',
      'Climate Control Full Auto A/C',
      'Air Conditioning',
      'Alloy Rims',
      'AM/FM Radio',
      'Front Camera',
      'Rear Camera',
      'Front & Rear Speakers',
      'Heated seats',
      'Immobilizer Key',
      'Navigation System',
      'Power Locks',
      'Power Mirrors',
      'Power Steering',
      'Power Windows',
      'Rear AC Vents',
      'Steering Switches',
      'USB and Auxillary Cable'
    ],
    gallery: [
      '/Nissasn Note E/1.jpg',
      '/Nissasn Note E/2.jpg',
      '/Nissasn Note E/3.jpg',
      '/Nissasn Note E/4.jpg',
      '/Nissasn Note E/5.jpg',
      '/Nissasn Note E/6.jpg',
      '/Nissasn Note E/7.jpg',
      '/Nissasn Note E/8.jpg',
      '/Nissasn Note E/9.jpg',
      '/Nissasn Note E/10.jpg',
      '/Nissasn Note E/11.jpg',
      '/Nissasn Note E/12.jpg'
    ],
    description: `NISSAN NOTE ePower 1.2L Full Hybrid – 2021\nModel Year: 2021\nMileage: 30,000 KM\nFuel Type: Hybrid\nTransmission: Automatic\nRegistration: Un-Registered\nImport: Fresh Import July 2024\nBody Type: Hatchback\nColor: Pearl Silver\nPackage: Medalist\n\nHighlights:\nVerifiable Auction Sheet; Most Comfortable Hybrid Car; 5 View Cameras; Cruise Control with ACCA RADAR; Pro Pilot; Push Start & Key-Less Entry; Security Alarm System; LED Projector Head Beams; 3 Driving Modes (Normal/Power/Eco); 6 Air Bags; Winker Side Mirrors; 25+ KM/L Fuel Average (Verifiable); UV Glass Protection; ABS; Driver Arm Rest; Climate Control Full Auto A/C; Multimedia Steering; Navigation; Front/Rear Cameras; Heated Seats; Premium Wheels/Rims.`,
    specifications: {
      'Model Year': '2021',
      'Mileage': '30,000 KM',
      'Body Style': 'Hatchback',
      'Fuel Type': 'Hybrid',
      'Transmission': 'Automatic',
      'Registration': 'Un-Registered',
      'Import': 'Fresh Import July 2024',
      'Color': 'Pearl Silver',
      'Package': 'Medalist',
      'Engine': '1.2L e-Power Full Hybrid',
      'Safety': 'Nissan Safety Sense, Anti Collision, Lane Assist',
      'Cameras': '5 View Cameras',
      'Cruise Control': 'With ACCA RADAR, Pro Pilot',
      'Fuel Average': '25+ KM/L (Verifiable)',
      'Air Bags': '6',
      'Driving Modes': 'Normal / Power / Eco',
      'Glass': 'Ultraviolet Protection',
      'Brakes': 'ABS',
      'A/C': 'Climate Control Full Auto',
      'Condition': 'Used, Immaculate'
    }
  },
  {
    id: 1015,
    name: 'TESLA Model Y Standard Range - 2022',
    year: 2022,
    price: 0,
    originalPrice: 0,
    image: '/Tesla Model Y/1.jpg',
    brand: 'Tesla',
    model: 'Model Y',
    mileage: 4000,
    bodyStyle: 'Compact SUV',
    fuel: 'Electric',
    transmission: 'RWD',
    engine: 'Electric Power = 350 kW (469 hp), Torque = 600 Nm, RPM = 6100',
    location: 'Un-Registered, Import from Japan',
    badges: ['Used', '5 Seater', '4.5 Grade Auction Sheet', 'Fresh Import 2024'],
    features: [
      'TESLA Model Y (RWD) - Standard Range',
      'Model Year – 2022',
      'Fresh Import 2024',
      'Import from Japan',
      '5 Seater',
      '4.5 Grade Auction Sheet',
      'Beautiful Pearl White Color',
      'Black Interior',
      'Range 393 Km with A/C at Full Charged',
      'Full Charging within 40 Minutes at Commercial Charging Station',
      'Almost 6 Hours needed at House Portable Charging Adaptor',
      'Rear Wheel Drivetrain',
      'Top Speed 225 Km/Hr',
      '0-100 km/h in 6.90 Seconds',
      'ABS',
      'Air Bags',
      'Air Conditioning',
      'Alloy Rims',
      'Climate Control',
      'Cruise Control',
      'Front Camera',
      'Front Speakers',
      'Heated seats',
      'Immobilizer Key',
      'Keyless Entry',
      'Navigation System',
      'Power Locks',
      'Power Mirrors',
      'Power Steering',
      'Power Windows',
      'Rear AC Vents',
      'Rear Camera',
      'Rear Speakers',
      'Steering Switches',
      'Sun Roof',
      'USB and Auxillary Cable'
    ],
    gallery: [
      '/Tesla Model Y/1.jpg',
      '/Tesla Model Y/2.jpg',
      '/Tesla Model Y/3.jpg',
      '/Tesla Model Y/4.jpg',
      '/Tesla Model Y/5.jpg',
      '/Tesla Model Y/6.jpg',
      '/Tesla Model Y/7.jpg',
      '/Tesla Model Y/8.jpg',
      '/Tesla Model Y/10.jpg',
      '/Tesla Model Y/11.jpg',
      '/Tesla Model Y/12.jpg'
    ],
    description: `TESLA Model Y Standard Range - 2022\nYear: 2022\nMileage: 4,000 KM\nBody Style: Compact SUV\nFuel Type: Electric\nDrive Type: Rear Wheel Drive\nRegistration: Un-Registered\n\nTESLA Model Y (RWD)\nModel Year – 2022\nFresh Import 2024\nImport from Japan\n5 Seater\n4.5 Grade Auction Sheet\nBeautiful Pearl White Color\nBlack Interior\nRange 393 Km with A/C at Full Charged\nFull Charging within 40 Minutes at Commercial Charging Station\nAlmost 6 Hours needed at House Portable Charging Adaptor\n\nElectric Power = 350 kW (kilowatts)\nMechanical Power = 469 hp\nTorque = 600 Nm\nRPM = 6100\nTop Speed = 225 Km/Hr\nAcceleration 0-100 km/h in 6.90 Seconds\nRear Wheel Drivetrain\n\nBrand New Immaculate Condition Guaranteed`,
    specifications: {
      'Model Year': '2022',
      'Mileage': '4,000 KM',
      'Body Style': 'Compact SUV',
      'Fuel Type': 'Electric',
      'Drive Type': 'RWD',
      'Registration': 'Un-Registered',
      'Range (Full Charge)': '393 Km (A/C On)',
      'Charging Time (Commercial)': '40 Minutes',
      'Charging Time (Home)': '6 Hours',
      'Electric Power': '350 kW',
      'Mechanical Power': '469 hp',
      'Torque': '600 Nm',
      'RPM': '6100',
      'Top Speed': '225 Km/Hr',
      '0-100 km/h': '6.90 Seconds',
      'Seating Capacity': '5',
      'Color': 'Pearl White',
      'Interior': 'Black',
      'Condition': 'Used, Immaculate'
    }
  },
  {
    id: 1016,
    name: 'Toyota Tundra 1794 Edition - 2023',
    year: 2023,
    price: 0,
    originalPrice: 0,
    image: '/toyota tundra/1.jpg',
    brand: 'Toyota',
    model: 'Tundra',
    mileage: 32500,
    bodyStyle: 'Pick Up',
    fuel: 'Petrol',
    transmission: 'RWD',
    engine: '3.5L Twin-Turbo V6, 389 hp, 479 lb-ft, 10-speed automatic',
    location: 'Un-Registered, Fresh Import 2025',
    badges: ['Used', '1794 Edition', '2×4 RWD', 'Fresh Import 2025', 'CARFAX Verified'],
    features: [
      'Top of the Line Genuine 1794 Edition 2×4-wheel drive',
      'Model 2023 and Fresh Import 2025',
      '3.5-Liter Twin-Turbo V6 Powerful Performance Engine',
      '389 horsepower and 479 lb-ft of torque',
      '10-speed automatic transmission',
      'Power Cabin Foot Steps and Power Bed Steps',
      'Made in USA, 100% Genuine Verifiable CARFAX Report Available',
      '100% Genuine Body and Mileage',
      'Rich Cream Leather Upholstery with American walnut wood trim with Suede Accents',
      'Premium 1794 Edition Exterior Chrome-trimmed Grille',
      'Heated & Ventilated Memory Seats',
      'DCCA RADAR with Premium Auto Pilot',
      'LANE Keep Assist',
      'Blind Spot Mirrors',
      'Auto Parking',
      'Sunroof with Moonroof',
      'BF Goodrich Fresh Zero Meter 2024 Model Tires',
      'TOYOTA Original Alloy Rims',
      'Superior Multifunctional Xenon Headlights with Genuine S-FOG Lights',
      'Fuel Economy – Up to 8 Km/L in city and 10 Km/L on highway',
      'ABS',
      'Air Bags',
      'Air Conditioning',
      'Alloy Rims',
      'AM/FM Radio',
      'Bluetooth',
      'Climate Control',
      'Cruise Control',
      'DVD Player',
      'Front Camera',
      'Front Speakers',
      'Heated seats',
      'Immobilizer Key',
      'Keyless Entry',
      'Keyless start',
      'Leather seats'
    ],
    gallery: [
      '/toyota tundra/1.jpg',
      '/toyota tundra/2.jpg',
      '/toyota tundra/3.jpg',
      '/toyota tundra/4.jpg',
      '/toyota tundra/5.jpg',
      '/toyota tundra/6.jpg',
      '/toyota tundra/7.jpg',
      '/toyota tundra/8.jpg',
      '/toyota tundra/9.jpg',
      '/toyota tundra/10.jpg',
      '/toyota tundra/11.jpg',
      '/toyota tundra/12.jpg',
      '/toyota tundra/13.jpg'
    ],
    description: `Toyota Tundra 1794 Edition - 2023\nYear: 2023\nMileage: 32,500 KM\nBody Style: Pick Up\nFuel Type: Petrol\nDrive Type: Rear Wheel Drive\nRegistration: Un-Registered\n\nTOYOTA TUNDRA\nTop of the Line Genuine 1794 Edition 2×4-wheel drive\nModel 2023 and Fresh Import 2025\n3.5-Liter Twin-Turbo V6 Powerful Performance Engine\n389 horsepower and 479 lb-ft of torque\n10-speed automatic transmission\nPower Cabin Foot Steps and Power Bed Steps\nMade in USA, 100% Genuine Verifiable CARFAX Report Available\n100% Genuine Body and Mileage\nRich Cream Leather Upholstery with American walnut wood trim with Suede Accents\nPremium 1794 Edition Exterior Chrome-trimmed Grille\nHeated & Ventilated Memory Seats\nDCCA RADAR with Premium Auto Pilot\nLANE Keep Assist\nBlind Spot Mirrors\nAuto Parking\nSunroof with Moonroof\nBF Goodrich Fresh Zero Meter 2024 Model Tires\nTOYOTA Original Alloy Rims\nSuperior Multifunctional Xenon Headlights with Genuine S-FOG Lights\nFuel Economy – Up to 8 Km/L in city and 10 Km/L on highway\n\nAnd much much more\nBrand New and Immaculate Condition Guaranteed`,
    specifications: {
      'Model Year': '2023',
      'Mileage': '32,500 KM',
      'Body Style': 'Pick Up',
      'Fuel Type': 'Petrol',
      'Drive Type': 'RWD',
      'Registration': 'Un-Registered',
      'Engine': '3.5L Twin-Turbo V6',
      'Horsepower': '389 hp',
      'Torque': '479 lb-ft',
      'Transmission': '10-speed automatic',
      'Seats': 'Heated & Ventilated, Memory',
      'Safety': 'DCCA RADAR, Lane Keep Assist, Blind Spot',
      'Parking': 'Auto Parking',
      'Sunroof': 'Yes (Moonroof)',
      'Tires': 'BF Goodrich 2024',
      'Wheels': 'Toyota Original Alloy',
      'Headlights': 'Xenon with S-FOG Lights',
      'Fuel Economy (City/Highway)': '8 / 10 Km/L',
      'Condition': 'Used, Immaculate'
    }
  }
  ,
  {
    id: 1010,
    name: 'Honda Civic 1.5 - 2022',
    year: 2022,
    price: 0,
    originalPrice: 0,
    image: '/Honda civic 2022/1.jpg',
    brand: 'Honda',
    model: 'Civic Standard 1.5',
    mileage: 95000,
    bodyStyle: 'Sedan',
    fuel: 'Petrol',
    transmission: 'Automatic',
    engine: '1.5L Turbo, 180 HP @ 6000 RPM, 220 Nm @ 4500 RPM',
    location: 'Registered: Punjab',
    badges: ['Used', '4-door', 'Local Assembly', 'White Color'],
    features: [
      'Beautiful White Color',
      'Black Leather Interior',
      '1.5L Turbo Engine',
      'Horse Power 180 HP @ 6000 RPM',
      'Torque 220 Nm @ 4500 RPM',
      '16 inches Alloy Wheels',
      'Excellent Fuel Average',
      'Fuel Tank Capacity 47 L',
      'Electronic Brake-Force Distribution (EBD)',
      'Brake Assist (BA)',
      'Speed Sensing Auto Door Lock',
      'Hill Start Assist Control',
      'Traction Control',
      'Side Mirrors with Indicators',
      'Daytime Running Lights (DRLs)',
      'Adjustable Headlights',
      'ABS',
      'Air Bags',
      'Air Conditioning',
      'Alloy Rims',
      'AM/FM Radio',
      'Cruise Control',
      'Front Camera',
      'Front Speakers',
      'Immobilizer Key',
      'Keyless Entry',
      'Leather seats',
      'LED headlights',
      'Multimedia Steering',
      'Navigation System',
      'Power Locks',
      'Power Mirrors',
      'Power Steering',
      'Power Windows',
      'Rear AC Vents',
      'Rear Camera',
      'Touchscreen LCD',
      'Brand New and Immaculate Condition Guaranteed'
    ],
    gallery: [
      '/Honda civic 2022/1.jpg',
      '/Honda civic 2022/2.jpg',
      '/Honda civic 2022/3.jpg',
      '/Honda civic 2022/4.jpg',
      '/Honda civic 2022/5.jpg',
      '/Honda civic 2022/6.jpg',
      '/Honda civic 2022/7.jpg',
      '/Honda civic 2022/8.jpg',
      '/Honda civic 2022/9.jpg',
      '/Honda civic 2022/10.jpg',
      '/Honda civic 2022/11.jpg',
      '/Honda civic 2022/12.jpg'
    ],
    description: `Honda Civic Standard 1.5 - 2022\nModel Year: 2022\nMileage: 95,000 KM\nBody Style: Sedan\nFuel Type: Petrol\nDrive Type: FWD\nDoors: 4-door\nRegistration: Punjab\nAssembly: Local\nColor: Beautiful White\nInterior: Black Leather\n\nPerformance:\nHorse Power 180 HP @ 6000 RPM; Torque 220 Nm @ 4500 RPM; 1.5L Turbo; Excellent Fuel Average; Fuel Tank Capacity 47 L.\n\nSafety & Convenience:\nElectronic Brake-Force Distribution (EBD); Brake Assist (BA); Speed Sensing Auto Door Lock; Hill Start Assist Control; Traction Control; ABS.\n\nExterior & Lighting:\nSide Mirrors with Indicators; DRLs; Adjustable Headlights; 16 inches Alloy Wheels.\n\nInfotainment & Comfort:\nAM/FM Radio; Navigation System; Touchscreen LCD; Multimedia Steering; Front/Rear Camera; Front Speakers; Rear AC Vents; Power Windows/Locks/Mirrors/Steering; Keyless Entry; Immobilizer Key; Leather seats.\n\nBrand New and Immaculate Condition Guaranteed`,
    specifications: {
      'Model Year': '2022',
      'Mileage': '95,000 KM',
      'Body Style': 'Sedan',
      'Fuel Type': 'Petrol',
      'Drive Type': 'FWD',
      'Transmission': 'Automatic',
      'Doors': '4-door',
      'Registration': 'Punjab',
      'Assembly': 'Local',
      'Color': 'White',
      'Interior': 'Black Leather',
      'Engine': '1.5L Turbo',
      'Horse Power': '180 HP @ 6000 RPM',
      'Torque': '220 Nm @ 4500 RPM',
      'Wheels': '16" Alloy',
      'Fuel Average': 'Excellent',
      'Fuel Tank Capacity': '47 L',
      'Brakes': 'ABS, EBD, BA',
      'Safety': 'Traction Control, Hill Start Assist',
      'Lighting': 'DRLs, Adjustable Headlights',
      'Mirrors': 'Side Mirrors with Indicators',
      'Condition': 'Used, Immaculate'
    }
  },
  {
    id: 1011,
    name: 'Toyota Corolla Altis Grande X CVT-i 1.8 (Black Interior) - 2022',
    year: 2022,
    price: 0,
    originalPrice: 0,
    image: '/TOYOTA GRANDE/1.jpg',
    brand: 'Toyota',
    model: 'Corolla Altis Grande X CVT-i 1.8',
    mileage: 107000,
    bodyStyle: 'Sedan',
    fuel: 'Petrol',
    transmission: 'CVT',
    engine: '1800 cc',
    location: 'Registered In Islamabad',
    badges: ['Used', '4 Doors', 'Local Assembly', 'White Color', 'Sunroof'],
    features: [
      'Beautiful White Color',
      'Black Interior',
      'Local Assembly',
      '1800 cc Engine Capacity',
      'CVT-i Transmission',
      'Sunroof',
      'ABS',
      'AM/FM Radio',
      'Air Bags',
      'Air Conditioning',
      'Alloy Rims',
      'Cruise Control',
      'Immobilizer Key',
      'Keyless Entry',
      'Navigation System',
      'Power Locks',
      'Power Mirrors',
      'Power Steering',
      'Power Windows',
      'Touchscreen LCD',
      'Bluetooth Connectivity',
      'Rear Camera',
      'Climate Control',
      'Fog Lights',
      'Multi-Information Display',
      'Steering Wheel Controls',
      'ISOFIX Child Seat Anchors',
      'Traction Control',
      'Hill Start Assist',
      'Electronic Brake-Force Distribution (EBD)',
      'Brake Assist (BA)'
    ],
    gallery: [
      '/TOYOTA GRANDE/1.jpg',
      '/TOYOTA GRANDE/2.jpg',
      '/TOYOTA GRANDE/3.jpg',
      '/TOYOTA GRANDE/4.jpg',
      '/TOYOTA GRANDE/5.jpg',
      '/TOYOTA GRANDE/6.jpg',
      '/TOYOTA GRANDE/7.jpg',
      '/TOYOTA GRANDE/8.jpg',
      '/TOYOTA GRANDE/9.jpg',
      '/TOYOTA GRANDE/10.jpg',
      '/TOYOTA GRANDE/11.jpg',
      '/TOYOTA GRANDE/12.jpg'
    ],
    description: `Toyota Corolla Altis Grande X CVT-i 1.8 (Black Interior) - 2022\nModel Year: 2022\nMileage: 107,000 km\nFuel Type: Petrol\nTransmission: CVT-i\nRegistration: Islamabad\nColor: White\nAssembly: Local\nEngine Capacity: 1800 cc\nBody Type: Sedan\nLast Updated: Jul 20, 2025\nAd Ref #: 10320445\n\nFeatures:\nABS\nAM/FM Radio\nAir Bags\nAir Conditioning\nAlloy Rims\nCruise Control\nImmobilizer Key\nKeyless Entry\nNavigation System\nPower Locks\nPower Mirrors\nPower Steering\nPower Windows\nSunroof\nTouchscreen LCD\nBluetooth Connectivity\nRear Camera\nClimate Control\nFog Lights\nMulti-Information Display\nSteering Wheel Controls\nISOFIX Child Seat Anchors\nTraction Control\nHill Start Assist\nElectronic Brake-Force Distribution (EBD)\nBrake Assist (BA)\n\nBrand New & Immaculate Condition Guaranteed (In Sha Allah)`,
    specifications: {
      'Model Year': '2022',
      'Mileage': '107,000 KM',
      'Body Style': 'Sedan',
      'Fuel Type': 'Petrol',
      'Transmission': 'CVT-i',
      'Registration': 'Islamabad',
      'Color': 'White',
      'Interior': 'Black',
      'Assembly': 'Local',
      'Engine Capacity': '1800 cc',
      'Body Type': 'Sedan',
      'Last Updated': 'Jul 20, 2025',
      'Ad Ref #': '10320445',
      'ABS': 'Yes',
      'AM/FM Radio': 'Yes',
      'Air Bags': 'Yes',
      'Air Conditioning': 'Yes',
      'Alloy Rims': 'Yes',
      'Cruise Control': 'Yes',
      'Immobilizer Key': 'Yes',
      'Keyless Entry': 'Yes',
      'Navigation System': 'Yes',
      'Power Locks': 'Yes',
      'Power Mirrors': 'Yes',
      'Power Steering': 'Yes',
      'Power Windows': 'Yes',
      'Sunroof': 'Yes',
      'Touchscreen LCD': 'Yes',
      'Bluetooth Connectivity': 'Yes',
      'Rear Camera': 'Yes',
      'Climate Control': 'Yes',
      'Fog Lights': 'Yes',
      'Traction Control': 'Yes',
      'Hill Start Assist': 'Yes',
      'EBD': 'Yes',
      'Brake Assist (BA)': 'Yes',
      'Condition': 'Brand New & Immaculate (In Sha Allah)'
    }
  },
  {
    id: 1012,
    name: 'Toyota C-HR G-LED - 2017',
    year: 2017,
    price: 0,
    originalPrice: 0,
    image: '/TOYOTA CHAR/1.jpg',
    brand: 'Toyota',
    model: 'CHR',
    mileage: 69000,
    bodyStyle: 'Crossover',
    fuel: 'Hybrid',
    transmission: 'ECVT',
    engine: '1.8L Hybrid',
    location: 'Registered: Islamabad',
    badges: ['Used', '4 Doors', 'Top of the Line G-LED', '4.5 Grade Auction Sheet', 'Imported 2021'],
    features: [
      'Beautiful Pearl White Color, High Re-Sale Value',
      'Stunning Half Leather Black & Brown Interior',
      'Top of the Line G-LED Package',
      'Adaptive Cruise Control with RADAR',
      'TOYOTA Safety Sense with Lane Departure Assist',
      'Blind Spot Monitoring (BSM)',
      '12 Sensors for Auto Pilot DCCA',
      'Push Start, Key-Less Entry',
      'Latest Dual Hybrid Motor Technology',
      'Full Multimedia Steering',
      'Genuine TV, Navigation, Bluetooth, Back Camera',
      'Retractable Side Mirrors',
      'Auto Eco Idle Mode with Auto Engine Kill System',
      'Fuel Average 20 Km/L (In Sha Allah)',
      'Ultraviolet Glass Protection',
      'ABS Brakes with EBD Break Assist',
      'Active Headrest',
      'Climate Control Full Auto AC',
      'Genuine 18" Alloy Rims with Brand New Tires',
      'HID Projector Head Beams',
      'HID Front Grill Horizontal Show Lights',
      'Genuine LED Fog Lamps',
      'Airbags',
      'AM/FM Radio',
      'CD/DVD Player',
      'Front Speakers',
      'Heated seats',
      'Immobilizer Key',
      'Power Locks/Mirrors/Steering/Windows',
      'Premium Wheels/Rims',
      'Rear Camera & Speakers',
      'Steering Switches',
      'USB Charger'
    ],
    gallery: [
      '/TOYOTA CHAR/1.jpg',
      '/TOYOTA CHAR/2.jpg',
      '/TOYOTA CHAR/3.jpg',
      '/TOYOTA CHAR/4.jpg',
      '/TOYOTA CHAR/5.jpg',
      '/TOYOTA CHAR/6.jpg',
      '/TOYOTA CHAR/7.jpg',
      '/TOYOTA CHAR/8.jpg',
      '/TOYOTA CHAR/9.jpg',
      '/TOYOTA CHAR/10.jpg',
      '/TOYOTA CHAR/12.jpg'
    ],
    description: `TOYOTA CH-R 1.8 Hybrid G-LED - 2017\nModel Year: 2017\nMileage: 69,000 KM\nFuel Type: Hybrid\nTransmission: ECVT\nRegistration: Islamabad\nColor: Pearl White\nAssembly: Imported\nEngine Capacity: 1.8L Hybrid\nBody Type: Crossover\nImport Year: 2021\nAuction Grade: 4.5 Grade (Verifiable)\n\nHighlights:\nNew Elegant Muscular Shape; Half Leather Black & Brown Interior; Adaptive Cruise Control with RADAR; TOYOTA Safety Sense with Lane Departure Assist; Blind Spot Monitoring (BSM); 12 Sensors for DCCA; Push Start & Key-Less Entry; Latest Dual Hybrid Motor Technology; Full Multimedia Steering; Genuine TV, Navigation, Bluetooth, Back Camera; Retractable Side Mirrors; Auto Eco Idle & Engine Kill System; Fuel Average 20 Km/L (In Sha Allah); UV Glass Protection; ABS with EBD & Brake Assist; Climate Control Full Auto AC; 18\" Alloy Rims with Brand New Tires; HID Projector Head Beams; HID Front Grill Show Lights; LED Fog Lamps.`,
    specifications: {
      'Model Year': '2017',
      'Mileage': '69,000 KM',
      'Body Style': 'Crossover',
      'Fuel Type': 'Hybrid',
      'Transmission': 'ECVT',
      'Registration': 'Islamabad',
      'Color': 'Pearl White',
      'Assembly': 'Imported',
      'Engine Capacity': '1.8L Hybrid',
      'Doors': '4',
      'Import Year': '2021',
      'Auction Grade': '4.5',
      'Package': 'G-LED',
      'Safety': 'Toyota Safety Sense, BSM, 12 Sensors DCCA',
      'Cruise Control': 'Adaptive with RADAR',
      'Eco Features': 'Auto Eco Idle, Engine Kill System',
      'Infotainment': 'TV, Navigation, Bluetooth, Back Camera',
      'Wheels': '18" Alloy (Brand New Tires)',
      'Lighting': 'HID Projectors, LED Fog Lamps',
      'Fuel Average': '20 Km/L (In Sha Allah)',
      'Condition': 'Used, Immaculate'
    }
  },
  {
    id: 1013,
    name: 'Nissan Sakura X - 2022',
    year: 2022,
    price: 0,
    originalPrice: 0,
    image: '/Nissan Sakura/1.jpg',
    brand: 'Nissan',
    model: 'Sakura X',
    mileage: 2000,
    bodyStyle: 'Hatchback',
    fuel: 'Electric',
    transmission: 'FWD',
    engine: 'Electric Motor',
    location: 'Un-Registered, Fresh Import 2025',
    badges: ['Used', '4 Doors', 'Fresh Import 2025', '5A Grade Auction Sheet'],
    features: [
      'X Package',
      'Model Year 2022',
      'Fresh Import 2025',
      '5A Grade Verifiable Auction Sheet',
      'Full Multimedia Steering with Bluetooth, Navigation',
      'Original Nissan LCD',
      '360 Degree View 5 Camera',
      'Anti Lane Departure Assist',
      'Anti Collision System',
      'Front Both Heated Seat',
      '4 Speakers',
      'Auto High Beam with LED daytime running lights',
      'LED Rear Lights',
      'Retractable Auto Folding Door Mirrors',
      'Full Climate Control Air-Conditioner',
      'Tilt telescopic adjustable steering wheel',
      'ABS + EBD Brake assist',
      'Standard 6 Airbags including curtain Airbags',
      'Emergency brake assist with Anti-Collision System',
      'Range Around 250 Km on Single Charge (e-Pedal)',
      'Push Start with Keyless Entry',
      'Back Spoiler',
      'Back Auto Viper',
      'Nissan Original Alloy Wheels',
      'Just like a Zero Meter car',
      'AM/FM Radio',
      'Air Conditioning',
      'Alloy Rims',
      'Front Camera',
      'Front Speakers',
      'Heated seats',
      'Immobilizer Key',
      'Keyless Entry',
      'Navigation System',
      'Power Locks',
      'Power Mirrors',
      'Power Steering',
      'Power Windows',
      'Rear Camera',
      'Rear Seat Entertainment',
      'Rear Speakers',
      'Steering Switches',
      'USB and Auxillary Cable'
    ],
    gallery: [
      '/Nissan Sakura/1.jpg',
      '/Nissan Sakura/2.jpg',
      '/Nissan Sakura/3.jpg',
      '/Nissan Sakura/4.jpg',
      '/Nissan Sakura/5.jpg',
      '/Nissan Sakura/6.jpg',
      '/Nissan Sakura/7.jpg',
      '/Nissan Sakura/8.jpg',
      '/Nissan Sakura/9.jpg',
      '/Nissan Sakura/10.jpg',
      '/Nissan Sakura/11.jpg',
      '/Nissan Sakura/12.jpg'
    ],
    description: `Nissan Sakura X - 2022\nYear: 2022\nMileage: 2,000 KM\nFuel Type: Electric\nBody Type: Hatchback\nDrive Type: FWD\nDoors: 4\nRegistration: Un-Registered\n\nNISSAN Sakura X Package\nModel Year 2022\nFresh Import 2025\n5A Grade Verifiable Auction Sheet Attached\n\nHighlights:\n- Full Multimedia Steering with Bluetooth, Navigation\n- Original Nissan LCD\n- 360 Degree View (5 Cameras)\n- Anti Lane Departure Assist, Anti Collision System\n- Front Heated Seats (Both)\n- Auto High Beam with LED DRLs and LED Rear Lights\n- Retractable Auto Folding Door Mirrors\n- Full Climate Control A/C\n- Tilt-Telescopic Steering Wheel\n- ABS + EBD with Brake Assist\n- 6 Airbags including Curtain Airbags\n- Emergency Brake Assist with Anti-Collision System\n- Range Around 250 Km on Single Charge (e-Pedal)\n- Push Start with Keyless Entry\n- Back Spoiler, Back Auto Wiper\n- Nissan Original Alloy Wheels\n\nImmaculate Condition Guaranteed`,
    specifications: {
      'Model Year': '2022',
      'Mileage': '2,000 KM',
      'Body Style': 'Hatchback',
      'Fuel Type': 'Electric',
      'Drive Type': 'FWD',
      'Doors': '4',
      'Registration': 'Un-Registered',
      'Package': 'X',
      'Range (Single Charge)': 'Around 250 Km (e-Pedal)',
      'Safety': 'Lane Departure, Anti-Collision, 6 Airbags',
      'Cameras': '360° (5 Cameras)',
      'Lighting': 'LED DRLs, LED Rear Lights',
      'Brakes': 'ABS + EBD + BA',
      'Steering': 'Tilt-Telescopic, Multimedia Controls',
      'Infotainment': 'Nissan LCD, Bluetooth, Navigation',
      'Windows/Mirrors': 'Power Windows, Retractable Auto Folding Mirrors',
      'Seats': 'Front Heated Seats',
      'Condition': 'Used, Immaculate'
    }
  }
];