export const cars = [
  {
    id: 1001,
    name: 'TESLA Model X Dual Motor & Long Range - 2018',
    year: 2018,
    price: 0,
    originalPrice: 0,
    image: '/Tesla Model X/1.jpg',
    brand: 'Tesla',
    model: 'Model X',
    mileage: 33500,
    bodyStyle: 'Compact SUV',
    fuel: 'Electric',
    transmission: 'AWD/4WD',
    engine: 'Electric Power = 350 kW (469 hp), Torque = 600 Nm, RPM = 6100',
    location: 'Un-Registered, Import from Japan',
    badges: ['Used', '7 Seater', '4 Grade Auction Sheet', 'Fresh Import 2024'],
    features: [
      'Beautiful Pearl White Color',
      'Milky Cream White Interior',
      'Range 450 Km with A/C at Full Charged',
      'Full Charging within 40 Minutes at Commercial Charging Station',
      'Almost 6 Hours needed at House Portable Charging Adaptor',
      'Top Speed = 225 Km/Hr',
      'Acceleration from 0 to 100 km/h in 4.40 Seconds',
      'AWD Drivetrain',
      'Smart Air Suspension at Front & Back',
      'Brand New and Immaculate Condition Guaranteed (ALHAMDULILLAH)',
      'Much More Details are available upon demand'
    ],
    gallery: [
      '/Tesla Model X/1.jpg',
      '/Tesla Model X/2.jpg',
      '/Tesla Model X/3.jpg',
      '/Tesla Model X/4.jpg',
      '/Tesla Model X/5.jpg',
      '/Tesla Model X/6.jpg',
      '/Tesla Model X/7.jpg',
      '/Tesla Model X/8.jpg',
      '/Tesla Model X/9.jpg',
      '/Tesla Model X/10.jpg',
      '/Tesla Model X/11.jpg',
      '/Tesla Model X/12.jpg',
      '/Tesla Model X/13.jpg',
      '/Tesla Model X/14.jpg'
    ],
    description: `Model Year: 2018\nImport: Fresh import from Japan (2024)\nCondition: Brand new and immaculate (4 Grade Auction Sheet)\nSeating: 7 Seater\nColor: Beautiful Pearl White exterior with Milky Cream White interior\n\nPerformance & Power:\n- Electric Power: 350 kW (469 hp)\n- Torque: 600 Nm\n- Top Speed: 225 km/h\n- Acceleration: 0 to 100 km/h in 4.4 seconds\n- Drivetrain: All-Wheel Drive (AWD)\n- Suspension: Smart Air Suspension (front & rear)\n\nRange & Charging:\n- Range: 450 km with A/C on a full charge\n- Charging Time:\n  • 40 minutes at commercial fast charging stations\n  • Approximately 6 hours with home portable charging adaptor`,
    specifications: {
      'Model Year': '2018',
      'Mileage': '33,500 KM',
      'Body Style': 'Compact SUV',
      'Fuel Type': 'Electric',
      'Drive Type': 'AWD/4WD',
      'Seating Capacity': '7',
      'Auction Grade': '4',
      'Color': 'Pearl White',
      'Interior': 'Milky Cream White',
      'Range (Full Charge)': '450 Km (A/C On)',
      'Charging Time (Commercial)': '40 Minutes',
      'Charging Time (Home)': '6 Hours',
      'Electric Power': '350 kW',
      'Mechanical Power': '469 hp',
      'Torque': '600 Nm',
      'RPM': '6100',
      'Top Speed': '225 Km/Hr',
      '0-100 km/h': '4.40 Seconds',
      'Suspension': 'Smart Air Suspension (Front & Back)',
      'Condition': 'Brand New & Immaculate (ALHAMDULILLAH)'
    }
  },
  {
    id: 1002,
    name: 'TESLA Model X Dual Motor & Long Range - 2018 (Grey)',
    year: 2018,
    price: 0,
    originalPrice: 0,
    image: '/Tesla Model X Grey/1.jpg',
    brand: 'Tesla',
    model: 'Model X',
    mileage: 33500,
    bodyStyle: 'Compact SUV',
    fuel: 'Electric',
    transmission: 'AWD/4WD',
    engine: 'Electric Power = 350 kW (469 hp), Torque = 600 Nm, RPM = 6100',
    location: 'Un-Registered, Import from Japan',
    badges: ['Used', '7 Seater', '4.5 Grade Auction Sheet', 'Fresh Import 2023'],
    features: [
      'Silky Grey Exterior',
      'Milky Cream White Interior',
      '7 Seater',
      'Auction Grade 4.5 – Verified Clean Condition',
      'Smart Air Suspension (Front & Rear)',
      'All-Wheel Drive (AWD)',
      'Up to 450 km Range (A/C On)',
      'Fast Charging: 60 min (Commercial)',
      'Home Charging: 6 hours',
      'Immaculate Condition Guaranteed'
    ],
    gallery: [
      '/Tesla Model X Grey/1.jpg',
      '/Tesla Model X Grey/2.jpg',
      '/Tesla Model X Grey/3.jpg',
      '/Tesla Model X Grey/4.jpg',
      '/Tesla Model X Grey/5.jpg',
      '/Tesla Model X Grey/6.jpg',
      '/Tesla Model X Grey/7.jpg',
      '/Tesla Model X Grey/8.jpg',
      '/Tesla Model X Grey/9.jpg',
      '/Tesla Model X Grey/10.jpg',
      '/Tesla Model X Grey/11.jpg',
      '/Tesla Model X Grey/12.jpg',
      '/Tesla Model X Grey/13.jpg',
      '/Tesla Model X Grey/14.jpg'
    ],
    description: `Model Year: 2018\nImport: Imported from Japan in 2023\nAuction Grade: 4.5 Grade – Verified Clean Condition\nSeating Capacity: 7 Seater\nColor: Silky Grey Exterior with Milky Cream White Interior\n\nPerformance & Power:\n- Electric Power: 350 kW (469 hp)\n- Torque: 600 Nm\n- RPM: 6100\n- Top Speed: 225 km/h\n- Acceleration: 0 to 100 km/h in just 4.4 seconds\n- Drivetrain: All-Wheel Drive (AWD)\n- Suspension: Smart Air Suspension (Front & Rear)\n\nRange & Charging:\n- Range: Up to 450 km with A/C on full charge\n- Charging Time:\n  • About 60 minutes at commercial charging stations\n  • Around 6 hours with home portable charger\n\nGuaranteed immaculate condition.\n\nFor more details, feel free to contact us!`,
    specifications: {
      'Model Year': '2018',
      'Import': 'Japan (2023)',
      'Auction Grade': '4.5',
      'Seating Capacity': '7',
      'Color': 'Silky Grey',
      'Interior': 'Milky Cream White',
      'Electric Power': '350 kW (469 hp)',
      'Torque': '600 Nm',
      'RPM': '6100',
      'Top Speed': '225 km/h',
      '0-100 km/h': '4.4 seconds',
      'Drivetrain': 'AWD',
      'Suspension': 'Smart Air Suspension (Front & Rear)',
      'Range': 'Up to 450 km (A/C On)',
      'Charging Time (Commercial)': '60 min',
      'Charging Time (Home)': '6 hours',
      'Condition': 'Immaculate'
    }
  },
  {
    id: 1003,
    name: 'Toyota Prius HEV - 2023',
    year: 2023,
    price: 0,
    originalPrice: 0,
    image: '/Toyota Prius/1.jpg',
    brand: 'Toyota',
    model: 'Prius HEV',
    mileage: 8000,
    bodyStyle: 'Sedan',
    fuel: 'Hybrid',
    transmission: 'ECVT',
    engine: 'Hybrid System Net Power 194 hp (FWD) or 196 hp',
    location: 'Punjab',
    badges: ['Used', '4 Doors', 'Registered 2024'],
    features: [
      'ABS',
      'Air Conditioning',
      'Alloy Rims',
      'AM/FM Radio',
      'Bluetooth',
      'Cruise Control',
      'Electric Adjustable Seats',
      'Front Speakers',
      'Immobilizer Key',
      'Keyless Entry',
      'Keyless start',
      'Navigation System',
      'Power Locks',
      'Power Mirrors',
      'Power Seats',
      'Power Steering',
      'Power Windows',
      'Rear Camera',
      'Touchscreen LCD',
      'USB and Auxillary Cable'
    ],
    gallery: [
      '/Toyota Prius/1.jpg',
      '/Toyota Prius/2.jpg',
      '/Toyota Prius/3.jpg',
      '/Toyota Prius/4.jpg',
      '/Toyota Prius/5.jpg',
      '/Toyota Prius/6.jpg',
      '/Toyota Prius/7.jpg',
      '/Toyota Prius/8.jpg',
      '/Toyota Prius/9.jpg',
      '/Toyota Prius/10.jpg',
      '/Toyota Prius/11.jpg',
      '/Toyota Prius/12.jpg',
      '/Toyota Prius/13.jpg',
      
    ],
    description: `Toyota Prius Top Of the Line U Package\nModel – 2023\nRegistered – 2024\nHorsepower 150 hp @ 6000 rpm, 139 lb. -ft. @ 4400-5200 rpm.\nHybrid System Net Power 194 hp (FWD) or 196 hp.\nTransmission: Electronically controlled Continuously Variable Transmission (ECVT)\nDrive Type Front-Wheel Drive (FWD) or All-Wheel Drive (AWD).\n0-60 mph: 7.2 seconds.\nBrakes: 11.1-in vented disc/11.0-in disc.\nEntertainment Standard Bluetooth\n\nTons of much more features………………\nBrand New and Immaculate Condition Guaranteed (ALHAMDULILLAH)`,
    specifications: {
      'Model Year': '2023',
      'Registration': '2024',
      'Mileage': '8,000 KM',
      'Body Style': 'Sedan',
      'Fuel Type': 'Hybrid',
      'Doors': '4',
      'Horsepower': '150 hp @ 6000 rpm',
      'Torque': '139 lb.-ft. @ 4400-5200 rpm',
      'Hybrid System Net Power': '194 hp (FWD) / 196 hp',
      'Transmission': 'ECVT',
      'Drive Type': 'FWD / AWD',
      '0-60 mph': '7.2 seconds',
      'Brakes': '11.1-in vented disc/11.0-in disc',
      'Entertainment': 'Bluetooth',
      'Condition': 'Brand New & Immaculate (ALHAMDULILLAH)'
    }
  }
]; 